# Numpy Arrays

In [9]:
my_list = [1,2,3]

In [10]:
my_list

[1, 2, 3]

In [11]:
import numpy as np

In [12]:
arr = np.array(my_list)

In [13]:
arr

array([1, 2, 3])

In [14]:
my_mat  = [[1,2,3],[4,5,6],[7,8,9]]

In [15]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(0,10,2)
# arange(start, end, step-size)

array([0, 2, 4, 6, 8])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
np.random.rand(5)

array([0.97285785, 0.39800086, 0.39832478, 0.50571248, 0.50041498])

In [31]:
np.random.rand(5,5)

array([[0.15431139, 0.19529423, 0.27062957, 0.45076838, 0.61387553],
       [0.664279  , 0.18846983, 0.78382722, 0.23208829, 0.01183769],
       [0.41987131, 0.52535199, 0.99845816, 0.97412251, 0.76476291],
       [0.04104202, 0.86865245, 0.36814701, 0.20047746, 0.3675145 ],
       [0.89693129, 0.22389134, 0.8766441 , 0.03193513, 0.50479492]])

In [33]:
np.random.randn(2) # including nagative number

array([-0.82873594,  1.16990734])

In [34]:
np.random.randn(2,4)

array([[ 0.22809778, -1.43778345, -2.59889772,  0.47019276],
       [-0.61154522, -0.2810096 ,  0.78714821, -0.24294041]])

In [40]:
np.random.randint(1,100,(10,10))

array([[11, 82, 64, 89, 76, 46, 39, 88, 45, 82],
       [25, 91, 26, 29, 28, 98, 62, 70, 60,  7],
       [22, 96, 32, 97, 90, 79, 97, 10, 11, 19],
       [ 4, 36,  8, 61, 58, 49,  1, 61, 49, 88],
       [76, 89, 71, 80, 95, 15,  4, 75,  2, 57],
       [70, 84, 71, 65, 49, 19, 54, 38, 35, 84],
       [42, 74, 97, 26, 66, 83, 53,  8,  6, 41],
       [66, 66, 59, 79, 67, 42, 68, 75, 18, 51],
       [63, 77,  7,  6,  4, 81,  8, 52, 75, 86],
       [ 2, 15, 27, 32, 38, 66, 38, 62, 26, 10]])

In [41]:
arr = np.arange(25)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
ranarr = np.random.randint(0,50,10)

In [44]:
ranarr

array([41, 39, 30, 12, 45, 11, 49,  7,  5, 15])

In [46]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
ranarr.max()

49

In [48]:
ranarr.min()

5

In [50]:
ranarr.argmax() # index

6

In [51]:
ranarr.argmin() # index

8

In [52]:
arr.shape

(25,)

In [53]:
arr = arr.reshape(5,5)

In [54]:
arr.shape

(5, 5)

In [55]:
arr.dtype

dtype('int64')

In [56]:
from numpy.random import randint

In [57]:
randint(2,10)

6